//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Neis.FileCleanup.Service.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Neis.FileCleanup.Service.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -------------------------------------------------------------------------------
        ///    File Cleanup Service Command Line Help
        ///-------------------------------------------------------------------------------
        ///
        ///Usage: Neis.FileCleanup.Service.exe [-c] [-?]
        ///
        ///Options:
        ///
        ///   -c           Runs the program as a console application instead of a service
        ///
        ///   -?           Displays the help context.
        /// </summary>
        internal static string HelpContents {
            get {
                return ResourceManager.GetString("HelpContents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archiving {0} of {1} files to {2}..
        /// </summary>
        internal static string Status_Archiving {
            get {
                return ResourceManager.GetString("Status_Archiving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking {0} of {1} files..
        /// </summary>
        internal static string Status_CheckingFiles {
            get {
                return ResourceManager.GetString("Status_CheckingFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting {0} of {1} files..
        /// </summary>
        internal static string Status_Deleting {
            get {
                return ResourceManager.GetString("Status_Deleting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializing....
        /// </summary>
        internal static string Status_Initializing {
            get {
                return ResourceManager.GetString("Status_Initializing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading configurations.
        /// </summary>
        internal static string Status_LoadingConfigurations {
            get {
                return ResourceManager.GetString("Status_LoadingConfigurations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not running.
        /// </summary>
        internal static string Status_NotRunning {
            get {
                return ResourceManager.GetString("Status_NotRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready.
        /// </summary>
        internal static string Status_Ready {
            get {
                return ResourceManager.GetString("Status_Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removing {0} of {1} empty folders.
        /// </summary>
        internal static string Status_RemovingEmptyFolders {
            get {
                return ResourceManager.GetString("Status_RemovingEmptyFolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving configurations.
        /// </summary>
        internal static string Status_SavingConfigurations {
            get {
                return ResourceManager.GetString("Status_SavingConfigurations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scanning {0} of {1} directories.
        /// </summary>
        internal static string Status_Scanning {
            get {
                return ResourceManager.GetString("Status_Scanning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searching for empty folders....
        /// </summary>
        internal static string Status_SearchForEmptyFolders {
            get {
                return ResourceManager.GetString("Status_SearchForEmptyFolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting....
        /// </summary>
        internal static string Status_Starting {
            get {
                return ResourceManager.GetString("Status_Starting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopping....
        /// </summary>
        internal static string Status_Stopping {
            get {
                return ResourceManager.GetString("Status_Stopping", resourceCulture);
            }
        }
    }
}
