//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Neis.Core.DataModel
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	/// <summary>
	/// Contains codes and information describing and/or relating to codes
	/// </summary>
	public partial class CodeInformation : DataObject
	{
		/// <summary>
		/// The code value
		/// </summary>
		public virtual string Code
		{
			get;
			set;
		}

		/// <summary>
		/// The code description
		/// </summary>
		public virtual string Description
		{
			get;
			set;
		}

	}
}

