//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Neis.Core.DataModel
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public partial class CodeList : DataObject
	{
		/// <summary>
		/// List of codes
		/// </summary>
		public virtual IEnumerable<CodeList> Codes
		{
			get;
			private set;
		}

		/// <summary>
		/// Name of this code list
		/// </summary>
		public virtual string Name
		{
			get;
			private set;
		}

	}
}

