//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Neis.Core.DataModel
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	/// <summary>
	/// Base data object
	/// </summary>
	public abstract partial class DataObject
	{
		/// <summary>
		/// Unique Identifier for this object
		/// </summary>
		public virtual int Id
		{
			get;
			set;
		}

	}
}

