//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Neis.Core.DataModel
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	/// <summary>
	/// Information for a gym member
	/// </summary>
	public partial class GymMember : DataObject
	{
		/// <summary>
		/// The identifier for the Person object
		/// </summary>
		protected virtual int PersonId
		{
			get;
			set;
		}

		/// <summary>
		/// Personal information about this member
		/// </summary>
		public virtual Person Person
		{
			get;
			set;
		}

		public virtual DateTime StartDate
		{
			get;
			set;
		}

		public virtual IEnumerable<Person> EmergencyContacts
		{
			get;
			set;
		}

	}
}

