//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Neis.Core.DataModel
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	/// <summary>
	/// Information for a person
	/// </summary>
	public partial class Person : DataObject
	{
		/// <summary>
		/// The name of this person
		/// </summary>
		public virtual Name Name
		{
			get;
			set;
		}

		/// <summary>
		/// The address for this person
		/// </summary>
		public virtual Location Address
		{
			get;
			set;
		}

		/// <summary>
		/// The identifier for the Name object
		/// </summary>
		protected virtual int NameId
		{
			get;
			set;
		}

		/// <summary>
		/// The for the address Location object
		/// </summary>
		protected virtual int AddressId
		{
			get;
			set;
		}

		/// <summary>
		/// The email address for this person
		/// </summary>
		public virtual string Email
		{
			get;
			set;
		}

		/// <summary>
		/// The phone numbers for this person
		/// </summary>
		public virtual IEnumerable<PersonPhone> PhoneNumbers
		{
			get;
			set;
		}

		/// <summary>
		/// The date of birth for this person
		/// </summary>
		public virtual DateTime DOB
		{
			get;
			set;
		}

		public virtual CodeInformation Gender
		{
			get;
			set;
		}

	}
}

