//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Neis.Core.DataModel
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	/// <summary>
	/// Information for a phone number
	/// </summary>
	public partial class Phone : DataObject
	{
		/// <summary>
		/// The area code
		/// </summary>
		public virtual int AreaCode
		{
			get;
			set;
		}

		/// <summary>
		/// The prefix
		/// </summary>
		public virtual int Prefix
		{
			get;
			set;
		}

		/// <summary>
		/// The suffix
		/// </summary>
		public virtual int Suffix
		{
			get;
			set;
		}

		/// <summary>
		/// The country code
		/// </summary>
		public virtual int CountryCode
		{
			get;
			set;
		}

		/// <summary>
		/// The extension
		/// </summary>
		public virtual int Extension
		{
			get;
			set;
		}

		/// <summary>
		/// The type of phone number
		/// </summary>
		public virtual CodeInformation Type
		{
			get;
			set;
		}

	}
}

